name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Run dotnet test
        run: dotnet test -c Release
